#!/bin/sh -e

cd ./$(git rev-parse --show-cdup)
if [ -e crawl-debug ] ; then
    echo "crawl checkout already exists, delete it to clone a new one."
else
    git clone git://gitorious.org/crawl/crawl.git crawl-debug
fi
